### ISSUE TITLE
nestk / cmake / FindFreenect.cmake libfreenect not found

### ISSUE THREAD

**Issue by pedropgusmao** [rgbdemo/nestk#12]
Hello again!
Sorry for being so annoying :)
I tried running the cmake configuration file ant this time it wouldn't find my libfreenect. I believe that, in line 29 of 'nestk / cmake / FindFreenect.cmake' file it should read NAME libfreenect, and not just freenect. 

 I am no expert on CMake, but I used the following configuration and it is working for me:

  ELSE (WIN32)
      FIND_PATH( FREENECT_INCLUDE_DIR libfreenect.h
          HINTS ${NESTK_ROOT_DIRS_HINTS}
          PATHS /usr /usr/local /sw /opt
          PATH_SUFFIXES include include/libfreenect libfreenect
          DOC "The directory where libfreenect.h resides")
      FIND_LIBRARY( FREENECT_LIBRARIES
          NAMES libfreenect.so
          PATHS /usr/local/lib64
          DOC "The freenect library")
  ENDIF (WIN32)

So I just put the final path on the PATHS and the NAMES I also included the .so extension.

Thanks

**Comment by nburrus** [comment]
Fixed here, there was a tipo:
https://github.com/nburrus/nestk/commit/aea8ce64980fd1d7857a3dbe7311ae803e40d457

Thanks for the report!

On Sat, Jun 30, 2012 at 9:08 PM, pedropgusmao
reply@reply.github.com
wrote:
