### ISSUE TITLE
Updating Openni

### ISSUE THREAD

**Issue by hackma** [rgbdemo/nestk#2]
Hello,

i need the automatic calibration via file (saveCalibrationdata(userid,filename)). So i have updated openni, nite and SensorKinect. Now i get many errors :(

Is it possible to update the used libs? or exists any method in nestk to load the calibrationdata via file?

Best Regards,
Marco

estk/ntk/libnestk.a(nite_rgbd_grabber.o): In function `xn::ImageGenerator::GetMetaData(xn::ImageMetaData&) const':
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:3086: undefined reference to`xnGetImageMetaData'
nestk/ntk/libnestk.a(nite_rgbd_grabber.o): In function `xn::UserGenerator::GetUserPixels(unsigned int, xn::SceneMetaData&) const':
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:4218: undefined reference to`xnGetUserPixels'
nestk/ntk/libnestk.a(nite_rgbd_grabber.o): In function `xn::UserGenerator::GetUsers(unsigned int*, unsigned short&) const':
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:4202: undefined reference to`xnGetUsers'
nestk/ntk/libnestk.a(nite_rgbd_grabber.o): In function `xn::SkeletonCapability::IsTracking(unsigned int) const':
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:3827: undefined reference to`xnIsSkeletonTracking'
nestk/ntk/libnestk.a(nite_rgbd_grabber.o): In function `xn::OutputMetaData::Free()':
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:211: undefined reference to`xnOSFreeAligned'
/workspace/mundus-nestk/nestk/deps/openni/Include/XnCppWrapper.h:211: undefined reference to `xnOSFreeAligned'
/workspace/mundus-nestk/nestk/deps/openni/In

**Comment by Shubhampatni86** [comment]
I also got same issue...if any one get solution for this then pls update here.
thanks
